// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybxVdBzvdKZxupO3nkV3o7SyjFdecOiM',
    appId: '1:439625179726:web:c47c6c58a1577a4ac5191f',
    messagingSenderId: '439625179726',
    projectId: 'e-mart-app-db656',
    authDomain: 'e-mart-app-db656.firebaseapp.com',
    storageBucket: 'e-mart-app-db656.appspot.com',
    measurementId: 'G-QNS7PYZCBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX682QiRfzwIpl9b_58IVsKyJkVIHC_wc',
    appId: '1:439625179726:android:e3eeebe7c526e197c5191f',
    messagingSenderId: '439625179726',
    projectId: 'e-mart-app-db656',
    storageBucket: 'e-mart-app-db656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdL5g-Pnsez5aHj8_aGa2oBPblIxmfQO4',
    appId: '1:439625179726:ios:bb692e27f0e37ad0c5191f',
    messagingSenderId: '439625179726',
    projectId: 'e-mart-app-db656',
    storageBucket: 'e-mart-app-db656.appspot.com',
    iosClientId: '439625179726-dqdu21kukhj07sedq3hmphsn3vk21k92.apps.googleusercontent.com',
    iosBundleId: 'com.example.eMartFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdL5g-Pnsez5aHj8_aGa2oBPblIxmfQO4',
    appId: '1:439625179726:ios:61a65b78df20fa42c5191f',
    messagingSenderId: '439625179726',
    projectId: 'e-mart-app-db656',
    storageBucket: 'e-mart-app-db656.appspot.com',
    iosClientId: '439625179726-bq6dgjc4kbm9f1o4m5h3uolqu878i8d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eMartFlutterApp.RunnerTests',
  );
}
